### ISSUE TITLE
Using Local Repo -- Uncaught Error: You must pass a block `type`.

### ISSUE THREAD

**Issue by kellyjosephprice** [GitbookIO/slate-edit-table#29]
I checked out `slate-edit-table` and `yarn link`ed into my other app. When I call `insertTable` I get the error below. I tried this against `master` and `0.8.4`.

```
block.js:143 Uncaught Error: You must pass a block `type`.
    at Function.create (http://localhost:3808/webpack/frontend.js:31596:35)
    at Object.block (http://localhost:3808/webpack/frontend.js:28144:30)
    at Object.Transforms.insertBlock (http://localhost:3808/webpack/frontend.js:223492:31)
    at Transform.Object.keys.forEach.Transform.(anonymous function) [as insertBlock] (http://localhost:3808/webpack/frontend.js:221152:32)
    at insertTable (http://localhost:3808/webpack/frontend.js:146533:20)
    at Toolbar.insertTable (http://localhost:3808/webpack/frontend.js:150653:19)
    at Toolbar.proxiedMethod (http://localhost:3808/webpack/frontend.js:214867:30)
    at GridSelect.insertTable (http://localhost:3808/webpack/frontend.js:150048:18)
    at GridSelect.proxiedMethod (http://localhost:3808/webpack/frontend.js:214867:30)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3808/webpack/frontend.js:59996:16)
    at executeDispatch (http://localhost:3808/webpack/frontend.js:38408:21)
    at Object.executeDispatchesInOrder (http://localhost:3808/webpack/frontend.js:38428:7)
    at executeDispatchesAndRelease (http://localhost:3808/webpack/frontend.js:24554:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3808/webpack/frontend.js:24565:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:3808/webpack/frontend.js:97619:9)
    at Object.processEventQueue (http://localhost:3808/webpack/frontend.js:24768:7)
    at runEventQueueInBatch (http://localhost:3808/webpack/frontend.js:204913:18)
    at Object.handleTopLevel [as _handleTopLevel] (http://localhost:3808/webpack/frontend.js:204924:5)
    at handleTopLevelImpl (http://localhost:3808/webpack/frontend.js:205006:24)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:3808/webpack/frontend.js:38771:20)
    at Object.batchedUpdates (http://localhost:3808/webpack/frontend.js:96405:26)
    at Object.batchedUpdates (http://localhost:3808/webpack/frontend.js:17126:27)
    at dispatchEvent (http://localhost:3808/webpack/frontend.js:205081:20)
```

**Comment by exah** [comment]
Hi, this error is result of usage of two Slate instances. Just tell webpack to use only project `node_modules` by setting absolute path in `resolve.modules = [ path.resolve(__dirname, 'node_modules')` in webpack config.

**Comment by kellyjosephprice** [comment]
Thanks!
